### ISSUE TITLE
Is the saiku-reporting-application is under development 

### ISSUE THREAD

**Issue by rajesh-wankhede** [Mgiepz/saiku-reporting-application#8]
Hello Mgiepz,
           i tried to integrate the saiku-reporting-application as a plugin to pentaho bi server 5.4  but 
 some ui api calls not matches to backend  written rest like for "[/report/{pageNo} ](url) "

**Comment by rajesh-wankhede** [comment]
i changed to rest payload
```
this.workspace.reportSpec.dataSource = new saiku.report.Datasource({
			id: "master",
			type: DatasourceType.CDA,
			queryString: mqlQueryString,
		});

```
And "[/report/1](url)" to [http://localhost:8080/pentaho/plugin/saiku-reporting/api/generator/webreport/1?nocache=Tue%20May%2009%202017%2013:03:14%20GMT+0530%20(IST)](url)

it throws `Caused by: org.pentaho.reporting.libraries.resourceloader.ResourceException
	at org.pentaho.reporting.platform.plugin.SimpleReportingComponent.getReport(SimpleReportingComponent.java:512)
	at org.saiku.reporting.backend.pho.component.ReportingComponentWrapper.getReport(ReportingComponentWrapper.java:90)
	at org.saiku.reporting.backend.service.ReportGeneratorService.getPrptTemplate(ReportGeneratorService.java:260)
`

is i am doing right or have some misconfig or installlaion.
